apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      imagePullSecrets:
        - name:  ghcr-secret
      containers:
        - name: chat-app-container
          image: ghcr.io/abobkeryousif/simple_chat_app:c79be95e99396c303b4c04cbf5896b6c2e4c9e2f
          ports:
            - containerPort: 8080
      resources:
        limits:
          memory: "300Mi" 
          cpu: "500m"
        requests:
          memory: "200Mi"
          cpu: "350m"

---

apiVersion:  v1
kind: Service
metadata:
  name:  chat-app-service
  namespace:  default
spec:
    selector:
      app:  chat-app
    ports:
      - port: 80
        targetPort:  8080
    type: ClusterIP
